# Generated by Django 2.2.2 on 2019-10-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('identify', models.CharField(default='f34060d8-f3f6-11e9-a9d1-7c67a28af84f', max_length=40, primary_key=True, serialize=False, verbose_name='身份ID')),
                ('username', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('register_time', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateField(auto_now=True, verbose_name='最后一次登陆时间')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='登陆邮箱')),
                ('auth_icon', models.ImageField(default='img/user.png', upload_to='img/', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
                ('is_admin', models.BooleanField(verbose_name='是否是管理员用户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'Auth',
                'ordering': ['-register_time', '-last_login'],
                'get_latest_by': '-register_time',
            },
        ),
    ]
